---
name: build-and-push-image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - build.sh
      - cni_plugins_version.env

  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read       # checkout the repo
      packages: write      # push to GHCR

    runs-on: ubuntu-24.04
    name: Build and Push new docker image
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: main

      - id: ghcr-io-login
        name: Login to GitHub Container Registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build-push-image
        name: Build and Push docker image
        run: ./build.sh --push
        shell: bash
